apiVersion: ENC[AES256_GCM,data:tzc=,iv:HhHSXFhx1iMuUTBRYN8LkuU5TuLCN0Yx8C3b5Y+NEgE=,tag:ky+Zeny7mqPZhH82jjXx8w==,type:str]
kind: ENC[AES256_GCM,data:SsmY7U/r,iv:yYAxEO4Ilx4DjYfF9jwRPh4zGQtaQb6otSNs84PKA9A=,tag:eBdxlSUW109ty6zAIZCzFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nP5xeFC9C7Fp6zp3axb5/kd6HtAdQdrJPWyy2Q==,iv:w7yC2UA+jwVaWA6Wi3uuThHYIxNHpz+1Mdh/l9eQvKM=,tag:7GSGFNXYoviNwtLpjWQ9Gg==,type:str]
    namespace: ENC[AES256_GCM,data:k5wbisckxQ==,iv:gDFt5TwWPmEBOAbHQlxwAptaGN8te3RUuzJcEasnMvc=,tag:LZzmEVg7nyXmIMIpoh+gng==,type:str]
type: ENC[AES256_GCM,data:0iiUeGnfk82zeGUtJ/uoovdUueQf3dS/,iv:+SuXJAlWH/9zDyL8IVoN1PJZIbITE3fh+x2F0/bzdA8=,tag:Za298jQ7HYThEkde87cIVg==,type:str]
stringData:
    username: ENC[AES256_GCM,data:J5+iVkA=,iv:OeAumKzAvmkcOAbVOL7YuU5CKnLF8fgYG1S1MGHN5zs=,tag:HwUh4ZW48Z6DwKlSiC3bzA==,type:str]
    password: ENC[AES256_GCM,data:Yx8KcMFvtjgI5A==,iv:BIt3DEE7H3pJyAMPWy5dobGt1jveAVn6yfymIqYsZHY=,tag:3wnUNKL4LDOvYboOmitueQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://fluxcd-dp1.vault.azure.net
          name: sops-cluster0
          version: 6a8770c55d98489880ca5db3ec6771b6
          created_at: "2024-07-30T00:00:42Z"
          enc: E3KmnK18tZqdmMVRjwSsi7hf0Bgk-mEi0hpKypw2pWoPi44i5N7tgUlb7F2rZMroON9L9-P7rsXwJNWWsh5BXrmLRuQCh9sD7GBI5anVdplR7k8ly7yH0OxmiaV1BqWT09GJY-CPy0wSmyLTa7zaXrCW79Qr2AxNfsXFHdDWkOE2KJ59stuEP90kMvu0dnDgBFQHue03D3yvNqLgkpTN_xWHbg18ou4cTFj1Y6OXtw7ajuEDvBU0OwNFUbGbu7RPsVlQM3pUQ8w1AnzxWcPb8Kuhz1_bu1Hh_1mMILz4e5xZz-7hin1GYHgFps_swMeIx0ksrsi9mj_s-nTlS9sYNw
    hc_vault: []
    age: []
    lastmodified: "2024-07-30T00:00:46Z"
    mac: ENC[AES256_GCM,data:7J3JZUWCpp54dHroLh48Dg1gUp8NZlYYxUTuhl2mqtZZVzig32FFETIbj8Jox3Q0cVk89g5t1XaRZU5rU3RFhTBNq9l0A4ceXnAtSsnq9YSnzKti2cXO1Ta8MbkNc5hKrc814G3RfQdcRuCGOgKU2DbknBdanKfnCocyEs4SNDI=,iv:OXgAeA1nVU/czKIN2cbp1KnWDqnqpFiOLcPsWSnU5tI=,tag:j1Abt2Fs+YIfGRXnjtN36w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
