apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: cluster-config
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: cluster-config
  path: ./wi-secrets-test
  prune: true
  decryption:
    provider: sops